import re
def chess_board(fen: str) -> str:
   fen_board = """........
                  ........
                  ........
                  ........
                  ........
                  ........
                  ........
                  ........
                  """
   fen_list = fen.split('/')
        #for i in fen_list:
   pass
fen = "4r2k/q5bp/4R3/4P1P1/P1Qn3R/2N5/1r4KP/8 w - - 1 43"
norm_fen = re.sub(r'w.*', "", fen).replace('/', '')
print(norm_fen)
board = """\
........
........
........
........
........
........
........
........\
"""





